// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1iFoNdx9Mcxyn7DIVbj6a3X_xlmDJfSI',
    appId: '1:64261344908:web:ebb0fb80420739809af5a9',
    messagingSenderId: '64261344908',
    projectId: 'cs310db',
    authDomain: 'cs310db.firebaseapp.com',
    storageBucket: 'cs310db.firebasestorage.app',
    measurementId: 'G-B281QCECJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1iFoNdx9Mcxyn7DIVbj6a3X_xlmDJfSI',
    appId: '1:64261344908:android:ebb0fb80420739809af5a9',
    messagingSenderId: '64261344908',
    projectId: 'cs310db',
    storageBucket: 'cs310db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1iFoNdx9Mcxyn7DIVbj6a3X_xlmDJfSI',
    appId: '1:64261344908:ios:ebb0fb80420739809af5a9',
    messagingSenderId: '64261344908',
    projectId: 'cs310db',
    storageBucket: 'cs310db.firebasestorage.app',
    iosBundleId: 'com.example.cs310TermProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1iFoNdx9Mcxyn7DIVbj6a3X_xlmDJfSI',
    appId: '1:64261344908:macos:ebb0fb80420739809af5a9',
    messagingSenderId: '64261344908',
    projectId: 'cs310db',
    storageBucket: 'cs310db.firebasestorage.app',
    iosBundleId: 'com.example.cs310TermProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1iFoNdx9Mcxyn7DIVbj6a3X_xlmDJfSI',
    appId: '1:64261344908:web:ebb0fb80420739809af5a9',
    messagingSenderId: '64261344908',
    projectId: 'cs310db',
    authDomain: 'cs310db.firebaseapp.com',
    storageBucket: 'cs310db.firebasestorage.app',
    measurementId: 'G-B281QCECJP',
  );
}
